### ISSUE TITLE
Entire Multisports Fitness Trend is recalculated (for past activities) if the FTP change

### ISSUE THREAD

**Issue by cornelurian** [thomaschampagne/stravistix#450] opened 2017-08-31 11:55 UTC
**Bug description:** 
I recently brought a power meter and after a couple of activities, I've got an approximative value (v0) for my FTP (not the correct one). I have updated the value in the Athlete Settings section, in the Cycling Functional Threshold Power (Watts) field. All the values for the Fitness, Fatigue and Form were calculated based on this v0 value of FTP.

After a FTP test, I've got another value (v1) for the FTP. I've updated the v0 with the v1 and the entire trend was recalculated based on the v1. Because v1>v0, the new fitness value was smaller than the initial fitness value.

I'm not sure if the this happens with all the values from the athlete settings (resting/max heartrate, or weight).

**Actual Behavior:** 
After the FTP update, the entire graph is recalculated and the values used to calculate the trend are smaller or bigger than the values before the update (depending of the new value of FTP).

**Expected Behavior:** 
Trend graph (and all the values for Fitness, Fatigue and Form) to not change for the activities from the past. Only the future activities to be calculated based on the new value of FTP.

**Steps to Reproduce:** 
-Take any trend graph
-Set an initial FTP value for your athlete settings (let say 200W)
-See the values
-Update the FTP with a different value (300W). I've selected 2 different values (not real) so the difference between them to be big enough to see the changes in the trend graph.

**Chrome version** 
Version 60.0.3112.113 (Official Build) (64-bit)

**Plugin version:** 
5.10.1 Stable

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by philipwhiuk** [comment] 2017-10-19 23:33
The proper fix is probably to store all FTP values at certain dates and visualise the FTP progression and then use those FTP values for activities in the various ranges.

**Comment by thomaschampagne** [comment] 2017-10-27 12:39
@philipwhiuk +1 i should maybe think about a solution around

Duplicate of https://github.com/thomaschampagne/stravistix/issues/456

**Closed by thomaschampagne** 2017-10-27 12:39 UTC
Labels: wontfix
