### ISSUE TITLE
Year Progressions

### ISSUE THREAD

**Issue by larrybike** [thomaschampagne/stravistix#463] opened 2017-09-30 03:49 UTC
**The Year Progressions only shows km & meters:** 

The old Year Progressions doesn't show under My Profile.
The old Year Progressions is much easier to read.

*Bug description:** 

**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** Version 61.0.3163.100 (Official Build) (64-bit)

**Plugin version:** 5.10.1

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by mbartenschlag** [comment] 2017-10-02 11:46
Duplicate of #461?

**Closed** 2017-10-02 17:32 UTC
Labels: duplicate
