### ISSUE TITLE
Zone settings: Zones reset when re-sync or toggle power in Fitness Trend view

### ISSUE THREAD

**Issue by tmt-xx** [thomaschampagne/stravistix#545] opened 2018-03-12 13:04 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: _____ 6.0.2 Stable
  * Chrome/Opera/Chromium version: _____Version 65.0.3325.124 (Official Build) beta (64-bit)
  * OS version: _____Linux
  
#### Steps to reproduce:

1. Set HR and Cycling zones as you like, remove most of them for example.
2a. Re-sync as suggested to get Fitness Trend to play with the new zones?
2b. Toggle power on and off in Fitness Trend view to see how power affects the trend
3. Go and see your Zones settings again, they're back to defaults

...Now I actually managed to reset Cycling power zones to defaults by doing hard-refresh after adjusting the zones and saving the settings.

#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?
No errors in console

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
I expected to zone settings stay as I have set them
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment] 2018-03-12 18:30
Strange. Are you that it's not https://github.com/thomaschampagne/stravistix/issues/498 ?

**Comment by tmt-xx** [comment] 2018-03-13 05:26
@thomaschampagne ah missed that, this indeed might be duplicate to that one.

**Comment by thomaschampagne** [comment] 2018-03-13 23:26
duplicate of  #498. Closing

**Closed by thomaschampagne** 2018-03-13 23:26 UTC
