### ISSUE TITLE
¿languages?

### ISSUE THREAD

**Issue by 1000io** [thomaschampagne/stravistix#99] opened 2015-06-26 19:38 UTC
Are you planing to create a "dictionary file" to translate all the aplication and the help?
Thanks!

**Comment by thomaschampagne** [comment] 2015-06-27 09:04
Yes. But need help for this. 

Any help for change code structure?

Tom

**Comment by praveentiru** [comment] 2016-05-26 14:52
@thomaschampagne Close this issue as it is duplicate of #10

**Comment by thomaschampagne** [comment] 2016-05-26 18:34
closed because of duplicate of #10

**Closed** 2016-05-26 18:34 UTC
