### ISSUE TITLE
multisport fitness graph misbehave

### ISSUE THREAD

**Issue by pent1** [thomaschampagne/stravistix#459] opened 2017-09-26 07:57 UTC
**Bug description:** 
activity is missing on fitness graph
**Actual Behavior:** 

multisport fitness graph not showing and not calculating yesterdays activity, but shows today and before yesterday.
Auto sync says that all activities are synced.
**Expected Behavior:** 
should show all activities.
**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
Version 61.0.3163.91 (Official Build) (64-bit)
**Plugin version:** 
5.11.0 Stable
**Activities links?:** 
this activity is missing in graph  https://www.strava.com/activities/1200632167
**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

(todo for me)
- [ ] Check link or not with #459

**Comment by thomaschampagne** [comment] 2017-10-22 01:34
Could you attach me original export of theses activities?
Ty

**Comment by thomaschampagne** [comment] 2017-10-22 01:35
- [ ] Check link or not with #459

**Comment by pent1** [comment] 2017-10-22 13:46
Thomas,

I checked it few minutes ago and everything is ok. I did not do anything it just fixed by itself.
do you want me to export strava activity as gpx?

**Comment by thomaschampagne** [comment] 2017-10-22 13:52
Yes ideally the original format from your gps device
FIT, TCX, GPX

**Comment by pent1** [comment] 2017-10-24 04:28
Thomas,
2017-09-25_11-10-02_4_302.fit was the one that had problem in fitness graph, but I included one before and one after so you can see that all three are good.
[garmin_src.tar.gz](https://github.com/thomaschampagne/stravistix/files/1409515/garmin_src.tar.gz)

**Comment by thomaschampagne** [comment] 2017-10-27 09:44
Hi @pent1,

I was not able to reproduce the problem yesterday evening.

Closing that ticket?!

Tom

**Closed** 2017-10-27 16:30 UTC
Labels: block, bug, ready
