### ISSUE TITLE
TypeError in AthleteStatsModifier.js causes year progressions not to load

### ISSUE THREAD

**Issue by geoffness** [thomaschampagne/stravistix#289] opened 2016-10-16 09:21 UTC
function sort returns "Uncaught TypeError: Cannot read property 'sort' of undefined" in AthleteStatsModifier.js:101

Browser is Chrome Version 54.0.2840.59 m

**Comment by thomaschampagne** [comment] 2016-10-16 09:38
Hi @geoffness .

Thanks for reporting this :). I'm not able to reproduce at the moment.

Which version of extension do you have?  version 4.3.1?

This happen on this page: https://www.strava.com/athletes/your_athlete_id ?

Thanks for your help. I will fix that asap !

Tom

**Comment by geoffness** [comment] 2016-10-16 23:35
Thanks Tom, yes my extension version is 4.3.1, and yes on my page
https://www.strava.com/athletes/12142789 the year progressions panel
doesn't load.

Thank you very much for getting back to me, and thanks for developing this
extension, I find it very helpful! :)

Geoff

On Sun, Oct 16, 2016 at 10:38 PM, Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment] 2016-10-17 09:43
Hi,

Damn didn't get error at home. Did you try to uninstall > reinstall extension?

Operating system?

What is the ID of plugin given at page: chrome://extensions/ ?

Thanks

**Comment by geoffness** [comment] 2016-10-18 09:01
Yep just tried reinstalling (now using version 4.3.2), same error as before.

OS is Windows 7

plugin ID is dhiaggccakkgdfcadnklkbljcgicpckn

Output from the Chrome console is as below if that helps:
A Parser-blocking, cross-origin script,
https://www.google.com/uds/?file=gdata&v=1.x, is invoked via
document.write. This may be blocked by the browser if the device has poor
network connectivity.
A Parser-blocking, cross-origin script,
https://www.google.com/uds/api/gdata/1.10/208a907929e7936990d2bf48205aa8d8/…ta,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js,
is invoked via document.write. This may be blocked by the browser if the
device has poor network connectivity.
ExtensionHasJustUpdated, localstorage clear
Uncaught TypeError: Cannot read property 'sort' of undefined
    at _loop_1
(chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/js/modifiers/AthleteStatsModifier.js:101:26)
    at AthleteStatsModifier.processData
(chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/js/modifiers/AthleteStatsModifier.js:148:13)
    at AthleteStatsModifier.init
(chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/js/modifiers/AthleteStatsModifier.js:13:14)
    at Array.<anonymous>
(chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/js/modifiers/AthleteStatsModifier.js:586:30)
    at c (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24:22275
)
    at Object.fireWith [as resolveWith] (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24:23087
)
    at Object.<anonymous> (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24:24407
)
    at c (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24:22275
)
    at Object.fireWith [as resolveWith] (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24:23087
)
    at n (
https://d3nn82uaxijpm6.cloudfront.net/assets/strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:25:27017
)
Failed to load resource: net::ERR_TIMED_OUT



On Mon, Oct 17, 2016 at 10:43 PM, Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment] 2016-10-18 13:19
Is the problem fixed with this build and with consistent results? [stravistix_v4.3.2_2016-10-18_13.15.47.zip](https://github.com/thomaschampagne/stravistix/files/536324/stravistix_v4.3.2_2016-10-18_13.15.47.zip)

**How to install standalone build:** https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

Thanks for your help :)

**Closed** 2016-10-18 20:07 UTC
Labels: bug

**Comment by geoffness** [comment] 2016-10-18 21:34
I'm going to be away from my computer for a few days but I will give it a try when I get back.

Thanks Tom :)

-----Original Message-----

**Comment by geoffness** [comment] 2016-10-25 18:15
Yep, this build seems to have resolved the problem. Thanks again :)
