### ISSUE TITLE
Dont seem to be able to configure heart rate zones down to my max HR of 168

### ISSUE THREAD

**Issue by Upinthehills** [thomaschampagne/stravistix#552] opened 2018-03-20 23:41 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here.

**Comment by Upinthehills** [comment] 2018-03-20 23:43
I have configured my max and min HR rate on the athlete section but this does not alter anything within the zones section. In zone 9 I can only reduce this to 205. I wish I had a max HR of 205

**Comment by thomaschampagne** [comment] 2018-03-24 23:42
Is your problem fixed in v6.0.3 ?

**Comment by Upinthehills** [comment] 2018-03-25 07:35
This was on a new download of the software so I am not sure. Should I reinstall this to find out.
Could I also say that I'd like to pay you something but the only option is to pay 25 pounds which is a little more than I can pay. What about putting options on the pay page.

Thanks Ali

Sent from BlueMail<http://www.bluemail.me/r?b=12512>
On 24 Mar 2018, at 11:43 pm, Thomas Champagne <notifications@github.com<mailto:notifications@github.com>> wrote:

Is your problem fixed in v6.0.3 ?

**Comment by thomaschampagne** [comment] 2018-03-25 14:29
Ok let me know if your problem is fixed. Because i fixed a bug on 6.0.3 which may fix yours.

You don't need to pay me ;) By the way you can change the value of the donation in the field.

Tom

**Comment by Upinthehills** [comment] 2018-03-30 08:42
Hi Tom,

Thanks I will pay you as I love it and am happy that you are out there doing your thing to make everyone else better cyclists. I use it a lot as I do many other apps.

Will I need to reload the new versions after deleting the old.

With my best regards,

Ali Marsh

________________________________

**Comment by thomaschampagne** [comment] 2018-03-31 15:01
@Upinthehills You have nothing to do. Just ensure that you have at least version 6.0.3.

Open strava and check that:

![image](https://user-images.githubusercontent.com/151973/38164433-fe50cf86-3504-11e8-83ec-c4fdbcef45d6.png)

Let me know if your problem is fixed or not. I could fix it in new version i will deploy tomorrow.

Tom

**Comment by ferrix** [comment] 2018-04-03 17:51
`ERROR Error: Uncaught (in promise): QUOTA_BYTES_PER_ITEM quota exceeded`

**Comment by thomaschampagne** [comment] 2018-04-03 19:07
@ferrix you are experiencing same issue described in the ticket?

This error means you want to sync too much data in chrome synced storage. Having to many zones could be the cause.


If error still there. Then think about reset settings from avanced menu

**Comment by ferrix** [comment] 2018-04-06 16:25
The zones are the defaults.

**Comment by thomaschampagne** [comment] 2018-04-06 16:42
Ok thanks. Potential link with https://github.com/thomaschampagne/stravistix/issues/568

Could you in the developer console (F12 key) enter these 3 commands and provide me results for each one:

**1**
```javascript
chrome.storage.sync.getBytesInUse((bytesInUse) => {
    let storage = {
        bytesInUse,
        quotaBytes: chrome.storage.sync.QUOTA_BYTES,
        percentUsage: bytesInUse / chrome.storage.sync.QUOTA_BYTES * 100,
    };
    console.log(storage);
});
```
**2**
```javascript
chrome.storage.sync.get(null, (data) => {
    function byteCount(s) {
        return encodeURI(s).split(/%..|./).length - 1;
    }
    console.log("User zones item size saved: " + byteCount(JSON.stringify(data)) + " bytes" );
});
```

**3**
```javascript
chrome.storage.sync.get(null, (data) => { // All synsec settings !
    console.log(JSON.stringify(data));
});
```

Thanks for your help !

**Comment by ferrix** [comment] 2018-04-06 18:03
1. ```{bytesInUse: 9474, quotaBytes: 102400, percentUsage: 9.251953125}```

2. ```User zones item size saved: 9691 bytes```

3. ```{"activateRunningCadence":true,"activateRunningGradeAdjustedPace":true,"activateRunningHeartRate":true,"activateRunningTemperature":true,"activityStravaMapType":"terrain","autoSyncMinutes":60,"bestSplitsConfiguration":null,"defaultLeaderBoardFilter":"overall","defaultLeaderboardFilter":"overall","displayActivityBestSplits":true,"displayActivityRatio":true,"displayAdvancedElevationData":true,"displayAdvancedGradeData":true,"displayAdvancedHrData":true,"displayAdvancedPowerData":true,"displayAdvancedSpeedData":true,"displayBikeOdoInActivity":true,"displayCadenceData":true,"displayExtendedGoals":false,"displayMotivationScore":true,"displayNearbySegments":true,"displayRecentEffortsHRAdjustedPace":true,"displayRecentEffortsHRAdjustedPacePower":false,"displayReliveCCLink":true,"displaySegmentRankPercentage":true,"displaySegmentTimeComparisonPosition":true,"displaySegmentTimeComparisonToCurrentYearPR":true,"displaySegmentTimeComparisonToKOM":true,"displaySegmentTimeComparisonToPR":true,"enableAlphaFitnessTrend":false,"enableBothLegsCadence":false,"extensionHasJustUpdated":false,"feedAutoScroll":true,"feedHideChallenges":false,"feedHideCreatedRoutes":false,"feedHideRideActivitiesUnderDistance":0,"feedHideRunActivitiesUnderDistance":0,"hidePremiumFeatures":true,"localStorageMustBeCleared":true,"remoteLinks":true,"reviveGoogleMaps":true,"reviveGoogleMapsLayerType":"terrain","showHiddenBetaFeatures":false,"targetsYearRide":5000,"targetsYearRun":750,"temperatureUnit":"C","userFTP":262,"userGender":"men","userMaxHr":193,"userRestHr":42,"userSwimFTP":50,"userWeight":122,"windUnit":"m/s","zones":{"ascent":[{"from":0,"to":100},{"from":100,"to":200},{"from":200,"to":300},{"from":300,"to":400},{"from":400,"to":500},{"from":500,"to":600},{"from":600,"to":700},{"from":700,"to":800},{"from":800,"to":900},{"from":900,"to":1000},{"from":1000,"to":1100},{"from":1100,"to":1200},{"from":1200,"to":1300},{"from":1300,"to":1400},{"from":1400,"to":1500},{"from":1500,"to":1600},{"from":1600,"to":1700},{"from":1700,"to":1800},{"from":1800,"to":1900},{"from":1900,"to":2000},{"from":2000,"to":2100},{"from":2100,"to":2200},{"from":2200,"to":2300},{"from":2300,"to":2400},{"from":2400,"to":2500},{"from":2500,"to":2600},{"from":2600,"to":2700},{"from":2700,"to":2800},{"from":2800,"to":2900},{"from":2900,"to":3000},{"from":3000,"to":3100},{"from":3100,"to":3200},{"from":3200,"to":3300},{"from":3300,"to":3400},{"from":3400,"to":3500},{"from":3500,"to":3600},{"from":3600,"to":3700},{"from":3700,"to":3800},{"from":3800,"to":3900},{"from":3900,"to":4000},{"from":4000,"to":4100},{"from":4100,"to":4200},{"from":4200,"to":4300},{"from":4300,"to":4400},{"from":4400,"to":4500},{"from":4500,"to":4600},{"from":4600,"to":4700},{"from":4700,"to":5000},{"from":5000,"to":5500}],"cyclingCadence":[{"from":0,"to":5},{"from":5,"to":10},{"from":10,"to":15},{"from":15,"to":20},{"from":20,"to":25},{"from":25,"to":30},{"from":30,"to":35},{"from":35,"to":40},{"from":40,"to":45},{"from":45,"to":50},{"from":50,"to":52},{"from":52,"to":54},{"from":54,"to":56},{"from":56,"to":58},{"from":58,"to":60},{"from":60,"to":62},{"from":62,"to":64},{"from":64,"to":66},{"from":66,"to":68},{"from":68,"to":70},{"from":70,"to":72},{"from":72,"to":74},{"from":74,"to":76},{"from":76,"to":78},{"from":78,"to":80},{"from":80,"to":82},{"from":82,"to":84},{"from":84,"to":86},{"from":86,"to":88},{"from":88,"to":90},{"from":90,"to":92},{"from":92,"to":94},{"from":94,"to":96},{"from":96,"to":98},{"from":98,"to":100},{"from":100,"to":102},{"from":102,"to":104},{"from":104,"to":106},{"from":106,"to":108},{"from":108,"to":110},{"from":110,"to":115},{"from":115,"to":120},{"from":120,"to":125},{"from":125,"to":130}],"elevation":[{"from":0,"to":100},{"from":100,"to":200},{"from":200,"to":300},{"from":300,"to":400},{"from":400,"to":500},{"from":500,"to":600},{"from":600,"to":700},{"from":700,"to":800},{"from":800,"to":900},{"from":900,"to":1000},{"from":1000,"to":1100},{"from":1100,"to":1200},{"from":1200,"to":1300},{"from":1300,"to":1400},{"from":1400,"to":1500},{"from":1500,"to":1600},{"from":1600,"to":1700},{"from":1700,"to":1800},{"from":1800,"to":1900},{"from":1900,"to":2000},{"from":2000,"to":2100},{"from":2100,"to":2200},{"from":2200,"to":2300},{"from":2300,"to":2400},{"from":2400,"to":2500},{"from":2500,"to":2600},{"from":2600,"to":2700},{"from":2700,"to":2800},{"from":2800,"to":2900},{"from":2900,"to":3000},{"from":3000,"to":3100},{"from":3100,"to":3200},{"from":3200,"to":3300},{"from":3300,"to":3400},{"from":3400,"to":3500},{"from":3500,"to":3600},{"from":3600,"to":3700},{"from":3700,"to":3800},{"from":3800,"to":3900},{"from":3900,"to":4000},{"from":4000,"to":4100},{"from":4100,"to":4200},{"from":4200,"to":4300},{"from":4300,"to":4400},{"from":4400,"to":4500}],"grade":[{"from":-20,"to":-19},{"from":-19,"to":-18},{"from":-18,"to":-17},{"from":-17,"to":-16},{"from":-16,"to":-15},{"from":-15,"to":-14},{"from":-14,"to":-13},{"from":-13,"to":-12},{"from":-12,"to":-11},{"from":-11,"to":-10},{"from":-10,"to":-9},{"from":-9,"to":-8},{"from":-8,"to":-7},{"from":-7,"to":-6},{"from":-6,"to":-5},{"from":-5,"to":-4},{"from":-4,"to":-3},{"from":-3,"to":-2},{"from":-2,"to":-1},{"from":-1,"to":-0.5},{"from":-0.5,"to":0.5},{"from":0.5,"to":1},{"from":1,"to":2},{"from":2,"to":3},{"from":3,"to":4},{"from":4,"to":5},{"from":5,"to":6},{"from":6,"to":7},{"from":7,"to":8},{"from":8,"to":9},{"from":9,"to":10},{"from":10,"to":11},{"from":11,"to":12},{"from":12,"to":13},{"from":13,"to":14},{"from":14,"to":15},{"from":15,"to":16},{"from":16,"to":17},{"from":17,"to":18},{"from":18,"to":19},{"from":19,"to":20}],"heartRate":[{"from":57,"to":87},{"from":87,"to":102},{"from":102,"to":117},{"from":117,"to":125},{"from":125,"to":132},{"from":132,"to":140},{"from":140,"to":147},{"from":147,"to":155},{"from":155,"to":162},{"from":162,"to":170},{"from":170,"to":177},{"from":177,"to":185},{"from":185,"to":193},{"from":193,"to":208}],"pace":[{"from":60,"to":75},{"from":75,"to":90},{"from":90,"to":105},{"from":105,"to":120},{"from":120,"to":135},{"from":135,"to":150},{"from":150,"to":165},{"from":165,"to":180},{"from":180,"to":195},{"from":195,"to":210},{"from":210,"to":225},{"from":225,"to":240},{"from":240,"to":255},{"from":255,"to":270},{"from":270,"to":285},{"from":285,"to":300},{"from":300,"to":315},{"from":315,"to":330},{"from":330,"to":345},{"from":345,"to":360},{"from":360,"to":375},{"from":375,"to":390},{"from":390,"to":405},{"from":405,"to":420},{"from":420,"to":435},{"from":435,"to":450},{"from":450,"to":465},{"from":465,"to":480},{"from":480,"to":495},{"from":495,"to":510},{"from":510,"to":525},{"from":525,"to":540},{"from":540,"to":555},{"from":555,"to":570},{"from":570,"to":585},{"from":585,"to":600},{"from":600,"to":615},{"from":615,"to":630},{"from":630,"to":645},{"from":645,"to":660},{"from":660,"to":675},{"from":675,"to":690},{"from":690,"to":705},{"from":705,"to":720},{"from":720,"to":735},{"from":735,"to":750}],"power":[{"from":0,"to":25},{"from":25,"to":50},{"from":50,"to":75},{"from":75,"to":100},{"from":100,"to":125},{"from":125,"to":150},{"from":150,"to":175},{"from":175,"to":200},{"from":200,"to":225},{"from":225,"to":250},{"from":250,"to":275},{"from":275,"to":300},{"from":300,"to":325},{"from":325,"to":350},{"from":350,"to":375},{"from":375,"to":400},{"from":400,"to":425},{"from":425,"to":450},{"from":450,"to":475},{"from":475,"to":500},{"from":500,"to":525},{"from":525,"to":550},{"from":550,"to":575},{"from":575,"to":600},{"from":600,"to":625},{"from":625,"to":650},{"from":650,"to":675},{"from":675,"to":700},{"from":700,"to":725},{"from":725,"to":750},{"from":750,"to":775},{"from":775,"to":800},{"from":800,"to":825},{"from":825,"to":850},{"from":850,"to":875},{"from":875,"to":900},{"from":900,"to":925},{"from":925,"to":950},{"from":950,"to":975},{"from":975,"to":1000},{"from":1000,"to":1025},{"from":1025,"to":1050},{"from":1050,"to":1075},{"from":1075,"to":1100},{"from":1100,"to":1125},{"from":1125,"to":1150},{"from":1150,"to":1175},{"from":1175,"to":1200},{"from":1200,"to":1225},{"from":1225,"to":1250}],"runningCadence":[{"from":65,"to":66},{"from":66,"to":67},{"from":67,"to":68},{"from":68,"to":69},{"from":69,"to":70},{"from":70,"to":71},{"from":71,"to":72},{"from":72,"to":73},{"from":73,"to":74},{"from":74,"to":75},{"from":75,"to":76},{"from":76,"to":77},{"from":77,"to":78},{"from":78,"to":79},{"from":79,"to":80},{"from":80,"to":81},{"from":81,"to":82},{"from":82,"to":83},{"from":83,"to":84},{"from":84,"to":85},{"from":85,"to":86},{"from":86,"to":87},{"from":87,"to":88},{"from":88,"to":89},{"from":89,"to":90},{"from":90,"to":91},{"from":91,"to":92},{"from":92,"to":93},{"from":93,"to":94},{"from":94,"to":95},{"from":95,"to":96},{"from":96,"to":97},{"from":97,"to":98},{"from":98,"to":99},{"from":99,"to":100},{"from":100,"to":101},{"from":101,"to":102},{"from":102,"to":103},{"from":103,"to":104},{"from":104,"to":105}],"speed":[{"from":0,"to":5},{"from":5,"to":6},{"from":6,"to":7},{"from":7,"to":8},{"from":8,"to":9},{"from":9,"to":10},{"from":10,"to":11},{"from":11,"to":12},{"from":12,"to":14},{"from":14,"to":16},{"from":16,"to":18},{"from":18,"to":20},{"from":20,"to":22},{"from":22,"to":24},{"from":24,"to":26},{"from":26,"to":28},{"from":28,"to":30},{"from":30,"to":32},{"from":32,"to":34},{"from":34,"to":36},{"from":36,"to":38},{"from":38,"to":40},{"from":40,"to":42},{"from":42,"to":44},{"from":44,"to":46},{"from":46,"to":48},{"from":48,"to":50},{"from":50,"to":52},{"from":52,"to":54},{"from":54,"to":56},{"from":56,"to":58},{"from":58,"to":60},{"from":60,"to":65},{"from":65,"to":70},{"from":70,"to":75},{"from":75,"to":80},{"from":80,"to":85},{"from":85,"to":90},{"from":90,"to":95},{"from":95,"to":100}]}}```

**Comment by thomaschampagne** [comment] 2018-04-06 19:38
The QUOTA_BYTES_PER_ITEM for chrome synced data is 8,192 bytes

And you have 9691 bytes total on your zones.

As quick work around, try to reduce your the number of your zones to stay under 8,192 bytes.

As a violent solution you can "reset" your settings from the advanced menu and be less greedy on zones count :)

Anyway this is a problem, i have to re-think how chrome sync is managed too. I may switch this to the local storage and next provide a dedicated online sync solution (without quota per item limit).

Thanks !

**Comment by ferrix** [comment] 2018-04-07 10:33
The fact that you don't need a backend to sync is quite practical. What we lose in the process is copying sessions between browsers and the rather opinionated large number of zones in all dimensions or whatever the defaults are nowadays but I don't remember setting that to 15ish myself. That in turn leads (in my case) to going with the defaults for most settings since there is not a very practical way to sync between instances of stravistix. More accurately that is not anywhere front and center for me to do.

I would argue that storing the settings in a denser "digest" format would help in transfering the configuration between my instances. Let's say there was a 32-byte arbitrary-looking string that I could pass into a new browser and get the rest of the data from Strava. Alternatively, this could be piggybacked into a Strava field (yes, fragile).

By now, this is not the same issue but a brand new design to fix a completely different feature. Thanks and sorry :D

**Comment by ferrix** [comment] 2018-04-07 10:36
Okay, the reset path gives me the same error. <img width="427" alt="screenshot 2018-04-07 13 36 11" src="https://user-images.githubusercontent.com/34988/38454069-af39b822-3a68-11e8-96df-8ef93e099074.png">

**Comment by thomaschampagne** [comment] 2018-04-07 17:03
So you  no longer have QUOTA exceeded error and can add your LTHR?

**Comment by ferrix** [comment] 2018-04-07 20:42
Yes.

**Closed** 2018-04-08 09:08 UTC
