### ISSUE TITLE
FTP over time set to current date and forward.

### ISSUE THREAD

**Issue by Neo121183** [thomaschampagne/stravistix#569] opened 2018-04-08 16:56 UTC
When my FTP changes, this seem to be added to all the previous workouts, and change the entire chart.
When I measure my FTP today, it dident change my FTP in the past...

**Comment by thomaschampagne** [comment] 2018-04-08 18:30
Duplicate of https://github.com/thomaschampagne/stravistix/issues/332

It's a know issue. Strava lacks of persisted physical data to handle that problem.

I cover this problem this year with my own solution that store athlete physical data over time. To pick and choose the right data for each activity calculated

**Closed by thomaschampagne** 2018-04-08 18:30 UTC
