### ISSUE TITLE
Changing FTP recalulates intensity of historical efforts

### ISSUE THREAD

**Issue by CoopsGitHub** [thomaschampagne/stravistix#452] opened 2017-09-07 12:14 UTC
**Bug description:** 

When changing FTP in the extension, it reports you need to resync. When this is done the relative intensity is changed of historical efforts. This is poor, because those efforts were at that quoted FTP and not necessarily of the new one.

**Actual Behavior:** 

Changing FTP causes sync of history, and recalculates all previous workout intensity

**Expected Behavior:** 

Changing FTP does not recalculate prior workouts/rides

**Steps to Reproduce:** 
- Enter an FTP 
 - Upload a ride, note intensity
 - Change FTP, perform sync
 - view old activity and see new intensity factor

**Chrome version** 
60.0.3112.113

**Plugin version:** 
5.10.1

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by philipwhiuk** [comment] 2017-10-19 23:34
See https://github.com/thomaschampagne/stravistix/issues/450#issuecomment-338066266

**Comment by thomaschampagne** [comment] 2017-10-27 12:38
@philipwhiuk +1
Duplicate of https://github.com/thomaschampagne/stravistix/issues/456

**Closed by thomaschampagne** 2017-10-27 12:38 UTC
